#!/usr/bin/env bash
set -euo pipefail

# Defaults
CONAN_PROFILE="conan_profiles/clang"
BUILD_TYPE="Debug"
CMAKE_GENERATOR="Ninja"
CMAKE_PRESET=""
NO_BUILD="OFF"
NO_TESTS="OFF"
CLEAN="OFF"
SANITIZERS="ON"
CLANG_TIDY="ON"
ONLY_CONAN="OFF"

usage() {
  echo "Usage: $0 [--conan] [-p <conan_profile>] [-b <build_type>] [-g <cmake_generator>] [-P <cmake_preset>] [-n|--no-build] [--no-tests] [--clean] [--no-sanitizers] [--no-clang-tidy]"
  echo "      --conan          Run only conan install (disabled by default)"
  echo "  -p, --profile        Conan profile file (default: ${CONAN_PROFILE})"
  echo "  -b, --build-type     Build type for Conan/CMake (Debug/Release, default: ${BUILD_TYPE})"
  echo "  -g, --generator      CMake generator (default: ${CMAKE_GENERATOR})"
  echo "  -P, --preset         CMake preset name for configuration/build"
  echo "  -n, --no-build       Configure only; skip build/tests, optionally run clang-tidy"
  echo "      --no-tests       Do not run ctest after building"
  echo "  -c  --clean          Remove existing build directory before configuring"
  echo "      --no-sanitizers  Disable ENABLE_SANITIZERS in CMake (enabled by default)"
  echo "      --no-clang-tidy  Disable ENABLE_CLANG_TIDY in CMake (enabled by default)"
  echo "  -h, --help           Show this help message"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --conan)
      ONLY_CONAN="ON"
      shift 1
      ;;
    -p|--profile)
      [[ $# -lt 2 ]] && usage
      CONAN_PROFILE="$2"
      shift 2
      ;;
    -b|--build-type)
      [[ $# -lt 2 ]] && usage
      BUILD_TYPE="$2"
      shift 2
      ;;
    -g|--generator)
      [[ $# -lt 2 ]] && usage
      CMAKE_GENERATOR="$2"
      shift 2
      ;;
    -P|--preset)
      [[ $# -lt 2 ]] && usage
      CMAKE_PRESET="$2"
      shift 2
      ;;
    -n|--no-build)
      NO_BUILD="ON"
      shift 1
      ;;
    -c|--clean)
      CLEAN="ON"
      shift 1
      ;;
    --no-tests)
      NO_TESTS="ON"
      shift 1
      ;;
    --no-sanitizers)
      SANITIZERS="OFF"
      shift 1
      ;;
    --no-clang-tidy)
      CLANG_TIDY="OFF"
      shift 1
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      ;;
  esac
done

echo "[build.sh] Using configuration:"
echo "  profile       = ${CONAN_PROFILE}"
echo "  build_type    = ${BUILD_TYPE}"
echo "  generator     = ${CMAKE_GENERATOR}"
echo "  preset        = ${CMAKE_PRESET:-<auto>}"
echo "  no_build      = ${NO_BUILD}"
echo "  no_tests      = ${NO_TESTS}"
echo "  clean         = ${CLEAN}"
echo "  sanitizers    = ${SANITIZERS}"
echo "  clang-tidy    = ${CLANG_TIDY}"

if [[ "${CLEAN}" == "ON" ]]; then
  echo "[build.sh] Performing clean build: removing 'build' directory"
  rm -rf build
fi

echo "[build.sh] Creating build directory 'build'"
mkdir -p build

echo "[build.sh] Running Conan install"
# Conan install configured by profile, build type and CMake generator
conan install . \
  --profile "${CONAN_PROFILE}" \
  -s build_type="${BUILD_TYPE}" \
  -c tools.cmake.cmaketoolchain:generator="${CMAKE_GENERATOR}" \
  --build=missing

if [[ "${ONLY_CONAN}" == "ON" ]]; then
  exit
fi
# Use CMake preset generated by Conan based on build type,
# unless an explicit preset was provided.
if [[ -z "${CMAKE_PRESET}" ]]; then
  CMAKE_PRESET="conan-${BUILD_TYPE,}" 
fi

echo "[build.sh] Configuring with CMake preset '${CMAKE_PRESET}'"

cmake --preset "${CMAKE_PRESET}" \
  -DENABLE_SANITIZERS="${SANITIZERS}" \
  -DENABLE_CLANG_TIDY="${CLANG_TIDY}" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  
if [[ "${NO_BUILD}" == "OFF" ]]; then

  echo "[build.sh] Building with CMake preset '${CMAKE_PRESET}'"
  cmake --build --preset "${CMAKE_PRESET}"

  if [[ "${NO_TESTS}" == "OFF" ]]; then
    echo "[build.sh] Running tests in build/${BUILD_TYPE}"
    ctest --test-dir "build/${BUILD_TYPE}"
  else
    echo "[build.sh] Tests disabled (--no-tests); skipping ctest"
  fi

elif [[ "${CLANG_TIDY}" == "ON" ]]; then

  echo "[build.sh] No build requested; running clang-tidy only"
  run-clang-tidy -p="build/${BUILD_TYPE}"

else
  echo "[build.sh] No build requested and clang-tidy disabled; nothing more to do"
fi
