# File: .github/workflows/template-sync.yml

on:
  # cronjob trigger
  schedule:
  - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
  
env:
  SOURCE_BRANCH: main
  SOURCE_REPOSITORY: liquidgoo/cpp-template
  EMAIL: vl.yakshuk@gmail.com
  USERNAME: liquidgoo
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        if: github.repository != env.SOURCE_REPOSITORY
        # https://github.com/actions/checkout#usage
        # uncomment if you use submodules within the repository
        # with:
        #   submodules: true

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.5.2
        if: github.repository != env.SOURCE_REPOSITORY
        with:
          source_repo_path: ${{ env.SOURCE_REPOSITORY }}
          upstream_branch: ${{ env.SOURCE_BRANCH }}
          git_user_name: ${{ env.USERNAME }}
          git_user_email: ${{ env.EMAIL }}
